version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80" # HTTP port
      - "443:443" # HTTPS port
    volumes:
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx config file
      - /root/nginx/certs:/etc/ssl/certs # Folder containing SSL certificates
      - /root/growthsauras/dist:/usr/share/nginx/html # Built React app folder
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
