version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    volumes:
      - react-app:/app/build
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80" # HTTP port
      - "443:443" # HTTPS port
    volumes:
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx config file
      - /root/nginx/certs:/etc/ssl/certs # Folder containing SSL certificates
      - react-app:/usr/share/nginx/html # Mount the volume from react-app to Nginx for static files
    networks:
      - app-network
    depends_on:
      - react-app
    restart: always

volumes:
  react-app: # Declare the volume to share the build folder between containers

networks:
  app-network:
    driver: bridge
